CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS nudge_storage(
    id UUID DEFAULT UUID_generate_v4() primary key,
    nudge_id VARCHAR NOT NULL,
    sender VARCHAR,
    receiver VARCHAR,
    templates VARCHAR NOT NULL,
    process_id VARCHAR NOT NULL,
    count INT NOT NULL,
    status VARCHAR NOT NULL,
    created_date TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS leads(
       agentId  VARCHAR NOT NULL,
       customerName VARCHAR NOT NULL,
       mobileNumber VARCHAR NOT NULL,
       gender VARCHAR NOT NULL,
       catSource VARCHAR NOT NULL,
       dob DATE NOT NULL,
       alternateMobileNo VARCHAR NOT NULL,
       email VARCHAR NOT NULL,
       nationality VARCHAR NOT NULL,
       occupation VARCHAR NOT NULL,
       education VARCHAR NOT NULL,
       houseNo VARCHAR NOT NULL,
       pinCode VARCHAR NOT NULL,
       city VARCHAR NOT NULL,
       commHouseNo VARCHAR NOT NULL,
       commPinCode VARCHAR NOT NULL,
       commCity VARCHAR NOT NULL,
       campaign VARCHAR NOT NULL,
       investment VARCHAR NOT NULL,
       income VARCHAR NOT NULL,
       leadStatus VARCHAR NOT NULL,
       leadId VARCHAR NOT NULL,
       vymoId VARCHAR NOT NULL,
       probabilityClosure VARCHAR NOT NULL,
       mainCampaign VARCHAR NOT NULL,
       statusCodeId VARCHAR NOT NULL,
       productId VARCHAR NOT NULL,
       ageRange VARCHAR NOT NULL,
       leadOwnerId VARCHAR NOT NULL,
       assignToCode VARCHAR NOT NULL,
       layoutId VARCHAR NOT NULL,
       ratingId VARCHAR NOT NULL,
       vymoRatingId VARCHAR NOT NULL,
       completeAddress VARCHAR NOT NULL,
       fmdDate TIMESTAMP NOT NULL,
       lastActivityTime TIMESTAMP NOT NULL,
       customerId VARCHAR NOT NULL,
       selectStatus VARCHAR NOT NULL,
       callConnected VARCHAR NOT NULL,
       callNotConnected VARCHAR NOT NULL,
       leadPropensity VARCHAR NOT NULL,
       productPitched VARCHAR NOT NULL,
       depedendantProductPitched VARCHAR NOT NULL,
       remarks VARCHAR NOT NULL,
       leadPriority VARCHAR NOT NULL,
       crmRatingid VARCHAR NOT NULL,
       createTime TIMESTAMP NOT NULL,
       updateTime TIMESTAMP NOT NULL
);

insert
  into
  leads ("agentid",
  "customername",
  "mobilenumber",
  "gender",
  "catsource",
  "dob",
  "alternatemobileno",
  "email",
  "nationality",
  "occupation",
  "education",
  "houseno",
  "pincode",
  "city",
  "commhouseno",
  "commpincode",
  "commcity",
  "campaign",
  "investment",
  "income",
  "leadstatus",
  "leadid",
  "vymoid",
  "probabilityclosure",
  "maincampaign",
  "statuscodeid",
  "productid",
  "agerange",
  "leadownerid",
  "assigntocode",
  "layoutid",
  "ratingid",
  "vymoratingid",
  "completeaddress",
  "fmddate",
  "lastactivitytime",
  "customerid",
  "selectstatus",
  "callconnected",
  "callnotconnected",
  "leadpropensity",
  "productpitched",
  "depedendantproductpitched",
  "remarks",
  "leadpriority",
  "crmratingid",
  "createtime",
  "updatetime")
values ('737366',
'Basu k',
'6667988719',
'Male',
'Self Lead',
'01/12/2000',
'9090909090',
'ramesh@monocept.com',
'No',
'Salaried',
'Graduate',
'HA091',
'752030',
'Balugaon',
'HA091',
'752031',
'Banpur',
'Yes',
'Bonds',
'<5L',
'Fresh Lead',
'8587',
'8923',
'Hot',
'Tejas',
'123',
'1235',
'20-30',
'64538',
'64538',
'101108',
'1',
'High',
'near post office,khurda,Odisha,752030,India',
'2024-03-03T12:38:00.544+00:00',
'2024-03-03T12:38:00.544+00:00',
'43228838543',
'Connected',
'Meeting Scheduled',
'Call Ringing Not Answered',
'High',
'ULIP',
'MaxLife Flexi Wealth Advantage',
'remarks from agent',
'High',
'3',
'2024-03-03T12:38:00.544+00:00',
'2024-03-03T12:42:00.544+00:00');


create table if not exists user_details (
ssoId varchar not null,
agentCode varchar not null,
name varchar not null,
username varchar not null,
firebaseId varchar not null,
role varchar not null,
operatingSystem varchar not null,
status varchar not null,
email varchar not null,
phoneNumber varchar not null,
createdDate varchar not null,
updatedDate varchar not null,
createdBy varchar not null,
updatedBy varchar not null,
supervisorId varchar not null,
internalPersonCode varchar not null,
designation varchar not null,
designationName varchar not null,
channelCode varchar not null,
superAppRole varchar not null,
jwtToken varchar not null,
goCode varchar not null,
encPassword varchar not null
);

INSERT INTO user_details  (ssoId, agentCode, name, username, firebaseId, role, operatingSystem, status, email, phoneNumber, createdDate, updatedDate, createdBy, updatedBy, supervisorId, internalPersonCode, designation, designationName, channelCode, superAppRole, jwtToken, goCode, encPassword) VALUES
  ('ssoId_13c0e99917f5', '737366', 'name_bd1fb46f0180', 'username_e1e17d379cc8', 'deviceId_6c07fd116e00', 'role_923b4b5117d4', 'operatingSystem_986a31f172b9', 'status_2c6452af6bf5', 'email_b97153d87c34', 'phoneNumber_3a652a7ddaa6', '2024-04-13 11:14:54', '2024-04-13 11:14:54', 'createdBy_8d3ff6d39438', 'updatedBy_4afb305babe8', 'supervisorId_972fa1488d0b', 'internalPersonCode_373121f6c32e', 'designation_d9d836c07bef', 'designationName_a983bbe3b08a', 'channelCode_9ebed4e274db', 'superAppRole_5433e1c4017d', 'jwtToken_a0b97512b97a', 'goCode_58a1fd895c71', 'encPassword_eebd3a4fcc0d');

create table quote (

  qid varchar not null,
  income_benefit varchar not null,
  lead_id varchar not null,
  life_cover varchar not null,
  maturity_benefit varchar not null,
  monthly_premium varchar not null,
  plan_name varchar not null,
  plan_type varchar not null,
  policy_term varchar not null,
  premium_payment_term varchar not null
);
insert into quote (qid, income_benefit, lead_id, life_cover, maturity_benefit, monthly_premium, plan_name, plan_type, policy_term, premium_payment_term)
values('quid', 'income_benefit', '8587', 'life_cover', 'maturity_venefit', 'monthly_premium', 'plan_name', 'plan_type', 'policy_term', 'premium_payment_term');